### ISSUE TITLE
Implement alignment operator

### ISSUE THREAD

**Issue by boeckmann** [boeckmann/asm6502#11]
I am not yet sure what symbol to use for an alignment operator. I tend to use `//` So for example `@ // 8` would return the program counter aligned to the next multiple of eight. Alternatively a more expressive `align` keyword could be used.

**Comment by boeckmann** [comment]
Org and fill directive would look like this to generate a few bytes for alignment.
```
.org @ // 8
.fill @ // 8 - @
```
I consider that not to be so ugly that a separate .align directive would be nessessary.

**Comment by boeckmann** [comment]
Alternative:
```
.org @ align 8
.fill @ align 8 - @
```

**Comment by waltje** [comment]
I have ".align [n]" where n defaults to 2.

If aligning, it will insert $00 bytes until done.  Something like that?

--fred







On Tuesday, April 11, 2023 at 04:51:08 PM EDT, Bernd Böckmann ***@***.***> wrote: 







Alternative:
.org @ align 8
.fill @ align 8 - @

**Comment by waltje** [comment]
So,

          .align                    ; must be on word boundary
foo:    .word    $ffd2
         .byte    $ea

        .align 4                ; must be on doubleword boundary
tbl:    .dword  $fc00ffda
        .dword $foo ...

which makes it a little more clear than using fills.

--Fred
    




On Tuesday, April 11, 2023 at 04:48:36 PM EDT, Bernd Böckmann ***@***.***> wrote: 







Org and fill directive would look like this to generate a few bytes for alignment.
.org @ // 8
.fill @ // 8 - @

I consider that not to be so ugly that a separate .align directive would be nessessary.

**Comment by boeckmann** [comment]
Yes that is one of the intended use cases. I like the idea making it an operator, so it can be used everywhere an expression is allowed and is orthogonal to the .fill directive. But i must admit that the .align directive is more readable!

**Comment by boeckmann** [comment]
Implemented as .align directive by 58628d1.
