### ISSUE TITLE
Allow variables to be defined via command line

### ISSUE THREAD

**Issue by boeckmann** [boeckmann/asm6502#22]
Implemented by eee321b.

The syntax is:
```
asm6502  VAR=123
```
The numbers are parsed like the number literals in assembler sources. So binary etc. is supported.

**Comment by waltje** [comment]
I use -Dvarname[=value], with 'value' defaulting to 1.

Hopefully I will be able to put vasm on git sometime this week.






On Monday, April 24, 2023 at 11:15:41 AM EDT, Bernd Böckmann ***@***.***> wrote: 







Implemented by eee321b.

The syntax is:
asm6502  VAR=123

The numbers are parsed like the number literals in assembler sources. So binary etc. is supported.
