### ISSUE TITLE
Implement unary is-defined operator ?, prohibit undefined .IF argument, remove .IFDEF

### ISSUE THREAD

**Issue by boeckmann** [boeckmann/asm6502#28]
At the moment `?` is used to return an undefined value. But the following usage seems to be more convinient:
```
.IF ?VICE
.ENDIF
```
Testing for undefined value should be much more common than expressing an undefined value. Undefined value will become `.?`.

Undefined arguments to .IF can be prohibited. .IFDEF is redundant and can be removed. Both not decided yet.

**Comment by boeckmann** [comment]
? and .? are implemented by dd2eda9. Regarding .IF and .IFDEF, a final decision is not made yet.

**Comment by waltje** [comment]
Problem is, most developers are used to working with if/ifn/ifdef/ifndef, and only a few use the more esoteric ? operators, even more so if those developers are also using C or C++ ..

I am not going to do this, unless I get specific requests for it.








On Wednesday, April 26, 2023 at 03:56:39 AM EDT, Bernd Böckmann ***@***.***> wrote: 







At the moment ? is used to return an undefined value. But the following usage seems to be more convinient:
.IF ?VICE
.ENDIF

.IFDEF is then redundant and could get removed. The undefined value becomes .?.

**Comment by boeckmann** [comment]
leave .ifdef, .ifndef in for now.
