### ISSUE TITLE
Add diagnostic levels and non-optimal code warnings

### ISSUE THREAD

**Issue by boeckmann** [boeckmann/asm6502#29]
Add warning levels 0, 1 and 2:

- 0: no warnings
- 1: only .warning directives are processed
- 2: all warnings (especially non-optimal code)

Non-optimal code: where ZP,X and ZP,Y could be generated instead of ABS,X and ABS,Y

**Comment by boeckmann** [comment]
implemented by c204a96.

**Comment by boeckmann** [comment]
Also, ABS addressing mode is catched if ZP would be possible.

**Comment by waltje** [comment]
Please add the often-overlooked JSR/RTS.
    foo:    ...             jsr  bar            rts
which can be changed to a single "jmp bar".

Fred

    On Friday, April 28, 2023 at 10:00:34 AM EDT, Bernd Böckmann ***@***.***> wrote:  
 
 


Also, ABS addressing mode is catched if ZP would be possible.

**Comment by boeckmann** [comment]
Thanks, Fred! Did not have the first one on my radar!

**Comment by boeckmann** [comment]
jsr, rts optimization notice added by 53ccf38dbefc2991ae51df509be6afc2dd09474a.

**Comment by boeckmann** [comment]
> Please add the often-overlooked JSR/RTS.     foo:    ...             jsr  bar            rts which can be changed to a single "jmp bar".

```
code25.a65:42: notice: JSR followed by RTS can be replaced by JMP
kernal.rom: checksum byte at $E4AC = $81
basic.rom: checksum byte at $BF52 = $EC
```
Only one in the whole basic source. They did a good job back then 🙂

**Comment by waltje** [comment]
Good job.
Yeah, those guys knew what they were doing.  I met one of them, many years after, andwas duly impressed :)
I am busy with something (else) right now, but will return to the assembler next week.
Fred
code25.a65:42: notice: JSR followed by RTS can be replaced by JMPkernal.rom: checksum byte at $E4AC = $81
basic.rom: checksum byte at $BF52 = $EC

Only one in the whole basic source. They did a good job back then 🙂
